site_name: RLBot Wiki
site_url: https://wiki.rlbot.org/
repo_name: RLBot/RLBot
repo_url: https://github.com/RLBot/RLBot
edit_uri: https://github.com/RLBot/wiki/edit/main/docs/

theme:
  name: material
  logo: assets/rlbot-logo.svg
  favicon: assets/rlbot-logo.svg
  icon:
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: custom
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: custom
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    # Expand navigation folders by default
    - navigation.expand
    # Enable the footer
    - navigation.footer
    # Enables navigation without page reload
    - navigation.instant
    # Enable v4/v5 to be tabs at the top
    - navigation.tabs
    # Enable 'Edit this page' button
    - content.action.edit
    # search will display the likeliest completion for the last word
    - search.suggest

extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/zbaAKPt
    - icon: fontawesome/brands/github
      link: https://github.com/RLBot
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/RLBotOfficial
    - icon: fontawesome/brands/twitter
      link: https://x.com/RLBotOfficial
    - icon: fontawesome/brands/twitch
      link: https://www.twitch.tv/rlbotofficial

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  # Code block features
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
  # Enable code blocks in multiple language
  - pymdownx.superfences

plugins:
  - search
  - redirects:
      redirect_maps:
        'index.md': 'v5/index.md'
